import React from "react";
import { Metadata } from "next";
import PostsPage from "@/pages/PostsPage";

export const metadata: Metadata = {
  title: "Posts | My Blog",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <PostsPage />
    </>
  );
};

export default page;
