import ProfilePage from "@/pages/ProfilePage";
import { Metadata } from "next";

import React from "react";

export const metadata: Metadata = {
  title: "Profile | My Blog",
  description: "Generated by create next app",
};

const page = async () => {
  return (
    <>
      <ProfilePage />
    </>
  );
};

export default page;
